sdccSellLimit=0.8
sdccSellLimitNumber=200
info=sdcc-dev
username=didi
password={cipher}AQAzLV5oGRaIcQICX19Fw73ztzlPApI+haYFUuwMLUadf36GF35/k920951FARsYdyABENHS/gg7NZIzDISgs6d7k6/SsAzI813APjMXRIiAKoKvSnhYLFevPx8BeXwrp4mWgHxwqn86xrWkMkYyMtqlOBGwmFBeS79n77lglN+9qDGSIwkduzr8feyuN9d4cmf7l9NF18akNh8/h+0mQd94xx+ACSByfnX6b1wwG5GiRe+9c1xb9JTHLoYGhVID+jPi0wDY5LEQtFONKEcPuH1zJnkAMaxaKnSgRtGNTKmiZL0comGb2J5NLEdY/QEF4VS9cMpd4ZYKTK9XifEFzU/JsH+aMWtFjE+dYQQ7KnU7fOpzCjS3QNntPQSdWu4TFOk=
